[package]
name = "MyKcl"
edition = "v0.0.1"
version = "v0.0.1"

[dependencies]
MyOciKcl1 = "0.0.1"
MyKcl1 = { git = "https://github.com/test/MyKcl1.git", tag = "v0.0.2" }
OCIPkg = { oci = "oci://ghcr.io/kusionstack/opsrule", tag = "0.0.9" }
